In [2]:
#Numpy assignemnts:

import numpy as np
import random


In [ ]:
#Asgn-1: 1. (5,5)=>random b/w 1 to 20, then 3rd col get oned
# we need to create a 2D array which is empty
arr = np.empty((5,5), dtype=int)
for i in range(5):
    for j in range(5):
        arr[i][j] = random.randint(1,20)

print(arr)

for i in range(5):
    arr[i][2]= 1

#or we can do numpy slicing in arrays
#arr[:,2]= 1 
print(arr)


[[ 6  7  5 17  2]
 [19  4 20  8 17]
 [ 1  9  8 14  5]
 [13 10 17  9 14]
 [ 8 11 18 10 13]]
[[ 6  7  1 17  2]
 [19  4  1  8 17]
 [ 1  9  1 14  5]
 [13 10  1  9 14]
 [ 8 11  1 10 13]]


In [ ]:
#Asgn-1: 2. (4,4)=>random b/w 1 to 16, then all diag elems
#get zeroed

arr = np.empty((4,4), dtype=int)
print(arr[0].size)
for i in range(arr[0].size):
    for j in range(arr[0].size):
        arr[i][j] = random.randint(1, 16)


for i in range(arr[0].size):
    arr[i][i]= 0
print(arr)

#Shorter code :
#arr = np.random.randint(1, 17, size=(4, 4))  # values from 1 to 16
#np.fill_diagonal(arr, 0)                    # set diagonal to 0
#print(arr)

4
[[ 0  4  9  6]
 [ 7  0  5  2]
 [ 8 14  0 10]
 [ 6 16  7  0]]


In [ ]:
#Asgn-2: 1. create arr 6x6 fil rands as 1-36 adn then slice it
# from 3 to 5 and 2 to 4 row and col respectively

arr = np.random.randint(1, 37, (6,6))
print(arr)

arr= arr[2:5, 1:4]
print(arr)

[[25  2 20  4  1 28]
 [32 14 15 14 30 13]
 [10 19 25 20 11 32]
 [32 18 18 36 29 20]
 [ 7 27  9 19 35  6]
 [17 12 22 20  2  5]]
[[19 25 20]
 [18 18 36]
 [27  9 19]]


In [59]:
##Asgn-2: 2. create arr 5x5 fil rands as 1-25 and then slice border
arr=  np.random.randint(1,25,(5,5))
print(arr)
lst = list(arr[0:1,])
lst.append(list(arr[arr[0].size-1:,]))
lst.append(list(arr[1:arr[0].size-1,0:1]))
lst.append(list(arr[1:arr[0].size,arr[0].size-1:arr[0].size-1]))
print("asnwer")
print(lst)

#Shorter version:
#import numpy as np
#
#arr = np.random.randint(1, 25, (5, 5))
#print(arr)
#
#print(type(arr[0]))
#top = arr[0].tolist()
#bottom = arr[4].tolist()
#left = arr[1:4, 0].tolist()
#print(type(left))
#right = arr[1:4, 4].tolist()
#
## Combine all border elements into a flat list
#border_elements = top + bottom + left + right
#
#print("answer")
#print(border_elements)

[[10 18 17 22  4]
 [19 13  2 11  7]
 [ 6 17 23 21 10]
 [12 11 24 23  4]
 [ 5 12 24 16  9]]
asnwer
[array([10, 18, 17, 22,  4], dtype=int32), [array([ 5, 12, 24, 16,  9], dtype=int32)], [array([19], dtype=int32), array([6], dtype=int32), array([12], dtype=int32)], [array([], dtype=int32), array([], dtype=int32), array([], dtype=int32), array([], dtype=int32)]]


In [64]:
#Asgn-3: 1. create 2 arr 3x4 fil rands as 1-20 and arithmeticate it
arr1= np.random.randint(1,20,(3,4))
arr2= np.random.randint(1,20,(3,4))
print(arr1)
print(arr2)
a = arr1+arr2
s= arr1-arr2
m= arr1*arr2
d = ((arr1)/(arr2))
print(f"a: {a} \n, s: {s} \n, m: {m} \n, d: {d}")

[[10  1  2 11]
 [ 9 12  1  7]
 [19 17  1 19]]
[[17  5  4 10]
 [ 4 19 16 13]
 [12  2  5 16]]
a: [[27  6  6 21]
 [13 31 17 20]
 [31 19  6 35]] 
, s: [[ -7  -4  -2   1]
 [  5  -7 -15  -6]
 [  7  15  -4   3]] 
, m: [[170   5   8 110]
 [ 36 228  16  91]
 [228  34   5 304]] 
, d: [[0.58823529 0.2        0.5        1.1       ]
 [2.25       0.63157895 0.0625     0.53846154]
 [1.58333333 8.5        0.2        1.1875    ]]


In [79]:
arr2= np.random.randint(1,20,(4,4))
print(arr2)
lst = list() 
for i in range(4):
    lst = arr2.sum(axis=0).tolist()
lst

#arr2 = np.random.randint(1, 20, (4, 4))
#lst = arr2.sum(axis=1).tolist()
#print(lst)

[[11 14  9  7]
 [16 16  4 12]
 [12 16 14 11]
 [14 13  2 16]]


[53, 59, 29, 46]

In [86]:
arr= np.random.randint(1,20,(4,4))
print(arr)
mean = arr.mean()
dev = arr.std()
mode=  np.median(arr)
var = arr.var()
print(mean, dev, mode, var)

narr = (arr-mean)/dev
print(narr)

[[17 17 19 11]
 [ 6 15 14  5]
 [18 10 16  6]
 [ 6  8  4  8]]
11.25 5.080600358225394 10.5 25.8125
[[ 1.13175601  1.13175601  1.52541028 -0.04920678]
 [-1.03334245  0.73810175  0.54127461 -1.23016958]
 [ 1.32858314 -0.24603392  0.93492888 -1.03334245]
 [-1.03334245 -0.63968818 -1.42699671 -0.63968818]]


In [22]:
arr = np.random.randint(1, 10, (3,3))
print(arr)
arr1= np.random.randint(1,10,(3,))
print(arr1)
ar2 =arr + arr1
ar2

[[4 9 5]
 [5 4 2]
 [9 8 5]]
[7 2 7]


array([[11, 11, 12],
       [12,  6,  9],
       [16, 10, 12]], dtype=int32)

In [25]:
import math
arr = np.random.randint(1, 10, (3,3))
x= np.linalg.det(arr)
inv = np.linalg.inv(arr)
eig = np.linalg.eigvals(arr)
print(x)
print(inv)
print(eig)

-211.99999999999997
[[ 0.13207547 -0.11320755  0.03773585]
 [-0.11320755  0.06132075  0.14622642]
 [ 0.13207547  0.13679245 -0.21226415]]
[-3.29640804  4.74624875 13.55015929]


In [26]:
arr = np.random.randint(1, 10, (2,3))
arr1 = np.random.randint(1, 10, (3,2))

res= np.linalg.matmul(arr, arr1)
res

array([[ 41,  28],
       [129,  93]], dtype=int32)

In [31]:
arr = np.random.randint(1, 10, (3,3))
arr1 = arr.reshape((1,9))
#arr1
arr2 = arr1.reshape(9,1)
arr2

array([[6],
       [5],
       [6],
       [9],
       [7],
       [8],
       [6],
       [6],
       [4]], dtype=int32)

In [44]:
arr = np.random.randint(1, 40, (5,5))
print(arr)
#arr1 = arr.reshape(1, arr.size)
#print(arr1)
#arr = arr1.reshape(arr[0].size, arr[0].size)
#print(arr)

arr2 = arr.flatten()
#arr2

[[17 20 28 16 18]
 [32 22 14 24  2]
 [37 27 27 32 22]
 [15  3  7  2 20]
 [25  6 29  8 30]]


In [54]:
arr = np.random.randint(1, 21, size=(5, 5))
print(arr)
indexer = [[0, 0, -1,-1], [0, -1, 0 ,-1]]
r= [0, 0, -1,-1]
c= [0, -1, 0 ,-1]
print(arr[r,c])

[[20 20  2  5  8]
 [13 12 15  2  9]
 [13  6  4  7  4]
 [ 9  6  7 12 10]
 [ 8 17 18 16 13]]
[20  8  8 13]


In [46]:
arr = np.random.randint(1, 21, size=(5, 5))
print(arr)
arr[arr> 10]= 10
arr

[[19 18 12  7 12]
 [ 9 15  8 13 13]
 [ 5 11 19 10 19]
 [11  6  6 17 20]
 [13  3 18  1 16]]


array([[10, 10, 10,  7, 10],
       [ 9, 10,  8, 10, 10],
       [ 5, 10, 10, 10, 10],
       [10,  6,  6, 10, 10],
       [10,  3, 10,  1, 10]], dtype=int32)

In [55]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)



Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]
