In [ ]:
# Numpy fro Data Analysis
#command to install numpy in Jupyter Notebook
!pip install numpy


In [ ]:
import numpy as np
#create arrays using numpy
#create a 1D array:
#write simply np.array(arg) =>this arg can be list, tuple, etc
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape) #for 1D array =>(size,)

#create a 2D array by reshaping:
arr1.reshape(1,4) #=> this converts to a 2D array with 1 row-5 cols
#general syntax: reshape(x,y) for x rows and y cols

#creating a 2D array using np is possible by using nested lists(2d Lists)
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)
#Nd arrays in pythno are always rectangles or cuboidal

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [9]:
#Building arrays using inbuilt functions
#this makes the array from 0 to 10 based on differences of 2
#syntax for arange: np.arange(start, end, common_diff)

x = np.arange(0, 10, 2)
print(x)

[0 2 4 6 8]


In [ ]:
#Inbuilt methods to use with arrays in Numpy
#np.ones((x,y))=>create array with x row y col and all elems as 1
#np.eye(a) => create a identity matrix of x order

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.itemsize) #gives no of bits of data type used in array


(2, 3)
int64
6
8


In [13]:
#Numpy Vectorized operations
R1 = np.array([1, 2, 3, 4, 5])
R2 = np.array([10, 20, 30, 40, 50])
print(R1 + R2)
print(R1 - R2)
print(R1 * R2)
print(R1 / R2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

#we can modifify the elements of an array directly using array index
print(arr)
print(arr[0, 0])  # Access single element
print(arr[1:, 2:])  # Access subarray
print(arr[1:, 1:3])  # Access another subarray

#Working of the above code
#arr[0,0] =>Accesses the first element of the matrix
#arr[1:,2:] =>this accesses from thr first row and the second column
#this means whole rectangle beneath the element (1,2) will be selected
#arr[1:, 1:3] =>selects a sub rectangle starting from index 1 of row
#and index 1 col to index 3 col

#selection criteria:
#arr[a:b, x:y] => starts from a goes to b-1 and same x to y-1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


In [21]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

arr[0, 0] = 100
arr[1:2, 2:3] = 100

print(arr)

[[100   2   3   4]
 [  5   6 100   8]
 [  9  10  11  12]]


In [23]:
#Statistical Operations and Normalization
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
print(mean, std)
normalized_data = (data - mean) / std
print(normalized_data)

3.0 1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [ ]:
#Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5) #returns a boolean
print(data[data > 5])
print(data[(data >= 5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
