In [ ]:
# Numpy fro Data Analysis
#command to install numpy in Jupyter Notebook
!pip install numpy


In [ ]:
import numpy as np
#create arrays using numpy
#create a 1D array:
#write simply np.array(arg) =>this arg can be list, tuple, etc
arr1 = np.array([1,2,3,4])
print(arr1)
print(type(arr1))
print(arr1.shape) #for 1D array =>(size,)

#create a 2D array by reshaping:
arr1.reshape(1,4) #=> this converts to a 2D array with 1 row-4 cols
print(arr1)
#general syntax: reshape(x,y) for x rows and y cols

#creating a 2D array using np is possible by using nested lists(2d Lists)
arr2 = np.array([[1,2,3,4,5], [2,3,4,5,6]])
print(arr2)
print(arr2.shape)
#Nd arrays in pythno are always rectangles or cuboidal

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
[1 2 3 4]
[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [9]:
#Building arrays using inbuilt functions
#this makes the array from 0 to 10 based on differences of 2
#syntax for arange: np.arange(start, end, common_diff)

x = np.arange(0, 10, 2)
print(x)

[0 2 4 6 8]


In [ ]:
#Inbuilt methods to use with arrays in Numpy
#np.ones((x,y))=>create array with x row y col and all elems as 1
#np.eye(a) => create a identity matrix of x order

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.dtype)
print(arr.size)
print(arr.itemsize) #gives no of bits of data type used in array


(2, 3)
int64
6
8


In [13]:
#Numpy Vectorized operations
R1 = np.array([1, 2, 3, 4, 5])
R2 = np.array([10, 20, 30, 40, 50])
print(R1 + R2)
print(R1 - R2)
print(R1 * R2)
print(R1 / R2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]
[0.1 0.1 0.1 0.1 0.1]


In [ ]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

#we can modifify the elements of an array directly using array index
print(arr)
print(arr[0, 0])  # Access single element
print(arr[1:, 2:])  # Access subarray
print(arr[1:, 1:3])  # Access another subarray

#Working of the above code
#arr[0,0] =>Accesses the first element of the matrix
#arr[1:,2:] =>this accesses from thr first row and the second column
#this means whole rectangle beneath the element (1,2) will be selected
#arr[1:, 1:3] =>selects a sub rectangle starting from index 1 of row
#and index 1 col to index 3 col

#selection criteria:
#arr[a:b, x:y] => starts from a goes to b-1 and same x to y-1
#arr[, x:y] => starts from x to y-1
#arr[a:b,] => starts from a goes to b-1

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[[ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]


In [8]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])
arr[0][1]= 100
arr[1:2, 2:3] = 100

print(arr)

[[  1 100   3   4]
 [  5   6 100   8]
 [  9  10  11  12]]


In [23]:
#Statistical Operations and Normalization
data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std = np.std(data)
print(mean, std)
normalized_data = (data - mean) / std
print(normalized_data)

3.0 1.4142135623730951
[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [10]:
#Logical Operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(data > 5) #returns a boolean
print(data[data > 5]) #return the element satisfying the condition
print(data[(data >= 5) & (data <= 8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]


In [3]:
#Pandas- Data Frames and Series
#a data manipulation library
#series and data frames are two basic data structures of this library
#A Series is a one-dimensional array-like object that can hold any data
#A DataFrame is a two-dimensional, size-mutable and potentially
#heterogeneous tabular data structure with labeled axes.
#A dataframe is a like table or excel with named axes
#Series has only one data frame
#Data frame can have multiple columns
#!pip install pandas
import pandas as pd

data = [1, 2, 3, 4, 5]
series = pd.Series(data)
#print(series)


#series from a dictionary
data = {'a': 1, 'b': 2, 'c': 3}
series_dict = pd.Series(data)
print(series_dict)

#DataFrame via a dictionary
data = {
    'name': ['Krish', 'John', 'Jack'],
    'age': [25, 30, 45],
    'city': ['Bangalore', 'New York', 'Florida']
}
#df = pd.DataFrame(data)
#print(df)

data = [
    {'name': 'Krish', 'age': 32, 'city': 'Bangalore'},
    {'name': 'John', 'age': 34, 'city': 'Bangalore'},
    {'name': 'Jack', 'age': 32, 'city': 'Bangalore'}
]
df = pd.DataFrame(data)
print(df)


a    1
b    2
c    3
dtype: int64
    name  age       city
0  Krish   32  Bangalore
1   John   34  Bangalore
2   Jack   32  Bangalore


In [ ]:
df = pd.read_csv('data.csv')
df.tail(5) 
# df.tail() =>shows the number of records from the bottom
# df.head() =>shows the number of records from the top

Date Category  Value   Product  Sales Region
45  2023-02-15        B   99.0  Product2  599.0   West
46  2023-02-16        B    6.0  Product1  938.0  South
47  2023-02-17        B   69.0  Product3  143.0   West
48  2023-02-18        C   65.0  Product3  182.0  North
49  2023-02-19        C   11.0  Product3  708.0  North

In [4]:
data = [
    {'name': 'Krish', 'age': 32, 'city': 'Bangalore'},
    {'name': 'John', 'age': 34, 'city': 'Bangalore'},
    {'name': 'Jack', 'age': 32, 'city': 'JMD'}
]
df = pd.DataFrame(data)
#print(df)
#one column of data frame is a series, so in other words
#data frame is a collection of series(cols)

#to get one col: df['col header]
#to get one row: df.iloc[i] = >this give row of index i
#to get a certain position: df.loc[i][j] => certain element at (i,j)
#to get a certain position: df.iloc[i][j] => certain element at (i,j)
#df.loc[2][2]
#df.iloc[2][1]

df.at[1, 'age']
#to get a specific valye use at 
#df.at[index, 'col_name'] =>only uses row index
#df.iat[row_index, col_index] =>gives element at the index
#df.iat uses both col and row index

np.int64(34)

In [ ]:
#Adding a column in the data frame table:
df['salary']= [2000, 3000, 4000] #write the new column in form of list
#or a pandas series

df

#removing a column
#drop tells the pandas whether we want to delete a column or row
#when axis=1, we delete the column entry row wise, like 
#salary for 1st row gets delted then the second row and so on

#when axis =0, we delete each row entry column wise, like we delete
#an entry in the first row adn then move on with second and so on
df.drop('salary', axis=1)
#always while removing write a second arg axis as 1


name  age       city  salary
0  Krish   32  Bangalore    2000
1   John   34  Bangalore    3000
2   Jack   32        JMD    4000

In [48]:
df.drop('salary', axis=1, inplace=True)
#write inplace for a permanent operation
df

name  age       city
0  Krish   32  Bangalore
1   John   34  Bangalore
2   Jack   32        JMD

In [ ]:
#we can make cahnges to the whole cols b y:like
#df['col_name]= df['col_name] + 1 
#this increases all the values of the whole col by 1

#to remove rows: we just give row index to the data frame
df.drop(0)
df
#df.drop(0, inplace=True) =>this deletes the row permanently at index 0
df

name  age       city  salary
1  John   34  Bangalore    3000
2  Jack   32        JMD    4000

In [ ]:
#Using statistical analysis
#df.describe() =>gives us tools which have measure to describe/summary
#such as measures of central tendency(mean, mode, median)


In [11]:
#Reading data from sources using Pandas
from io import StringIO

data = '''{"employee_name": ["James"], "email": ["james@gmail.com"], "job_profile": ["Senior Developer"]}'''
df = pd.read_json(StringIO(data))
df

employee_name            email       job_profile
0         James  james@gmail.com  Senior Developer